import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,update,skill,chooseUpgrade,upgradeChoices,damage,collect,score,blocked,findPath,distance,HEROES,CHAPTERS,HAZARDS,PERKS} from '../lib/game/engine.ts';
const idle={x:0,y:0,fire:false,aim:null,interact:false,skill:false};
function run(s,secs,input=idle){for(let i=0;i<secs*60;i++)update(s,input,1/60);}
test('four named heroes, 8 chapters and complete 29-theme coverage',()=>{assert.deepEqual(HEROES.map(h=>h.name),['安禾','永勋','凌曜','观微']);assert.equal(CHAPTERS.length,8);assert.equal(HAZARDS.length,29);assert.equal(new Set(CHAPTERS.flatMap(c=>c.hazards)).size,29);});
test('every map, spawn, mandatory node and pickup is collision-safe and reachable',()=>{for(let c=0;c<8;c++)for(let st=0;st<3;st++){const s=createGame(0,c,st);for(const p of [...s.nodes,...s.pickups,...s.enemies]){assert.equal(blocked(s,p,p.r||19),false,`${c}/${st}: ${JSON.stringify(p)}`);assert.ok(findPath(s,p).length,`${c}/${st} no route to ${p.x},${p.y}`);}}});
test('movement normalized, bounds held, dash respects barriers',()=>{const a=createGame(),b=createGame();a.enemies=[];b.enemies=[];run(a,.4,{...idle,x:1});run(b,.4,{...idle,x:1,y:-1});assert.ok(Math.abs(distance(a.p,{x:120,y:790})-distance(b.p,{x:120,y:790}))<.01);run(a,20,{...idle,x:-1});assert.ok(a.p.x>=43);const s=createGame(2);s.p.x=280;s.p.y=300;skill(s,{...idle,x:1});assert.ok(s.p.x<301);});
test('role skills differ and cannot bypass cooldown',()=>{for(let h=0;h<4;h++){const s=createGame(h);s.p.hp=50;assert.equal(skill(s,{...idle,x:1}),true);assert.equal(skill(s,idle),false);assert.ok(s.buff>0);if(h===0)assert.equal(s.p.hp,75);if(h===2)assert.ok(s.p.x>120);}});
test('PPE gives matched protection only; pickups are finite',()=>{const a=createGame(),b=createGame();a.p.inv=0;b.p.inv=0;collect(a,a.pickups[0]);damage(a,20,0);damage(b,20,0);assert.ok(a.p.hp>b.p.hp);const old=a.gear.length;run(a,1);assert.equal(a.gear.length,old);});
test('boss cannot be shot through the source-control prerequisite',()=>{const s=createGame();s.enemies=s.enemies.filter(e=>e.boss);s.p.x=1160;s.p.y=500;s.p.inv=999;run(s,40);const boss=s.enemies[0];assert.equal(boss.dead,false);assert.ok(boss.hp>=boss.max*.65-.001);});
test('node interaction cannot skip order, progress resets away, upgrade pauses simulation',()=>{const s=createGame();s.enemies=[];s.p={...s.p,...s.nodes[2]};run(s,3,{...idle,interact:true});assert.equal(s.step,0);Object.assign(s.p,s.nodes[0]);run(s,.5,{...idle,interact:true});assert.ok(s.progress>0);run(s,1);assert.equal(s.progress,0);s.upgradePending=true;const t=s.time;run(s,5,{...idle,x:1});assert.equal(s.time,t);const choices=upgradeChoices(s);chooseUpgrade(s,1);assert.equal(s.perks.at(-1),choices[1].id);assert.equal(s.upgradePending,false);});
test('dynamic edition has unique map geometry, mechanics, events and 24 perks',()=>{const maps=CHAPTERS.map((c,i)=>{const s=createGame(0,i,2);return JSON.stringify({blocks:s.blocks,nodes:s.nodes,mechanic:c.mechanic,event:s.eventName});});assert.equal(new Set(maps).size,8);assert.equal(new Set(CHAPTERS.map(c=>c.mechanic)).size,8);assert.equal(PERKS.length,24);});
test('all five ordered steps complete, score reaches 100, terminal state freezes, fresh retry resets',()=>{const s=createGame();s.enemies=[];for(let i=0;i<5;i++){Object.assign(s.p,s.nodes[i]);run(s,2,{...idle,interact:true});assert.equal(s.step,i+1);}assert.equal(s.status,'won');assert.equal(score(s).total,100);const t=s.time;run(s,10);assert.equal(s.time,t);const f=createGame();f.p.inv=0;damage(f,1000,22);assert.equal(f.status,'lost');run(f,5);assert.equal(f.p.hp,0);const r=createGame();assert.equal(r.step,0);assert.equal(r.p.hp,100);assert.equal(r.time,0);});
test('long simulation does not leak projectiles or produce non-finite coordinates',()=>{const s=createGame();s.level=4;s.p.inv=99999;run(s,600);assert.ok(s.shotsList.length<100);assert.ok(s.rings.length<20);for(const e of s.enemies)assert.ok(Number.isFinite(e.x)&&Number.isFinite(e.hp));});
