'use client';
/* Canvas game state intentionally lives in refs and is sampled by a throttled UI tick. */
/* eslint-disable react-hooks/refs, react-hooks/set-state-in-effect */
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ShieldCheck,ArrowRight,ScanLine,BookOpen,Gamepad2,Pause,Volume2,VolumeX,Check,Target,Zap,Footprints,Hand,Home,Download,Share2,Smartphone} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {HEROES,HAZARDS,CHAPTERS,GEAR,createGame,update,chooseUpgrade,score,distance,findPath,type State,type Input} from '@/lib/game/engine';
import {render,camera,type Assets} from '@/lib/game/render';
const stages=['识别入门','组合挑战','综合处置'];
const basePath=process.env.NEXT_PUBLIC_BASE_PATH??'';
const initialInput=():Input=>({x:0,y:0,fire:false,aim:null,interact:false,skill:false});
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
function Portrait({index,className=''}:{index:number,className?:string}){return <div aria-hidden="true" className={'portrait '+className} style={{backgroundImage:`url(${basePath}/assets/heroes.webp)`,backgroundPosition:`${index%2*100}% ${Math.floor(index/2)*100}%`}}/>}
function HazardArt({sprite}:{sprite:number}){return <div className="hazard-art" style={{backgroundImage:`url(${basePath}/assets/hazards.webp)`,backgroundPosition:`${sprite%4*100/3}% ${Math.floor(sprite/4)*100}%`}}/>}
function clock(t:number){return `${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;}
type RecordMap=Record<string,{score:number,time:number}>;
export default function Page(){
 const [hero,setHero]=useState(0),[chapter,setChapter]=useState(0),[stage,setStage]=useState(0),[difficulty,setDifficulty]=useState(0),[playing,setPlaying]=useState(false),[paused,setPaused]=useState(false),[help,setHelp]=useState(false),[installHelp,setInstallHelp]=useState(false),[installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null),[installed,setInstalled]=useState(false),[sound,setSound]=useState(false),[assetsReady,setAssetsReady]=useState(false),[assetError,setAssetError]=useState(false),[records,setRecords]=useState<RecordMap>({}),[tick,setTick]=useState(0),[auto,setAuto]=useState(true);
 const game=useRef<State|null>(null),canvas=useRef<HTMLCanvasElement>(null),arena=useRef<HTMLDivElement>(null),assets=useRef<Assets|null>(null),input=useRef(initialInput()),keys=useRef(new Set<string>()),size=useRef({w:1000,h:600}),pausedRef=useRef(false),audioRef=useRef<AudioContext|null>(null),soundRef=useRef(false),joy=useRef({x:0,y:0,id:-1}),joyRef=useRef<HTMLDivElement>(null),saved=useRef(false),route=useRef<{x:number,y:number}[]>([]),interactLatch=useRef(false),pressAt=useRef(0);
 const [stick,setStick]=useState({x:0,y:0});
 useEffect(()=>{try{const parsed=JSON.parse(localStorage.getItem('hse-frontier-records-v1')||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))setRecords(parsed);}catch{}let alive=true;const imgs={} as Assets;Promise.all((['heroes','hazards','floor'] as const).map(k=>new Promise<void>((ok,no)=>{const img=new Image();img.onload=()=>{imgs[k]=img;ok();};img.onerror=no;img.src=basePath+'/assets/'+k+'.webp';}))).then(()=>{if(alive){assets.current=imgs;setAssetsReady(true);}}).catch(()=>{if(alive)setAssetError(true);});return()=>{alive=false};},[]);
 useEffect(()=>{if('serviceWorker'in navigator)void navigator.serviceWorker.register(basePath+'/sw.js',{scope:(basePath||'')+'/'}).catch(()=>{});const standalone=window.matchMedia('(display-mode: standalone)').matches||('standalone'in navigator&&(navigator as Navigator&{standalone?:boolean}).standalone===true);setInstalled(standalone);const before=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent);};const done=()=>{setInstalled(true);setInstallPrompt(null);};window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',done);};},[]);
 async function requestInstall(){if(installPrompt){await installPrompt.prompt();const result=await installPrompt.userChoice;if(result.outcome==='accepted')setInstalled(true);setInstallPrompt(null);return;}setInstallHelp(true);}
 useEffect(()=>{pausedRef.current=paused||help;interactLatch.current=false;input.current=initialInput();keys.current.clear();joy.current.id=-1;setStick({x:0,y:0});},[paused,help]);
 useEffect(()=>{soundRef.current=sound;},[sound]);
 function beep(frequency=500){if(!soundRef.current)return;try{const a=audioRef.current;if(!a)return;const o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=frequency;g.gain.setValueAtTime(.025,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.start();o.stop(a.currentTime+.12);}catch{}}
 function toggleSound(){const value=!sound;if(value){try{audioRef.current??=new AudioContext();void audioRef.current.resume();}catch{}}setSound(value);}
 function start(c=chapter,st=stage){const g=createGame(hero,c,st,difficulty);g.auto=auto;game.current=g;setChapter(c);setStage(st);saved.current=false;route.current=[];interactLatch.current=false;input.current=initialInput();keys.current.clear();setPaused(false);setPlaying(true);setTick(0);}
 function home(){setPlaying(false);setPaused(false);setHelp(false);game.current=null;input.current=initialInput();keys.current.clear();}
 useEffect(()=>{if(!playing)return;const el=arena.current;if(!el)return;const resize=()=>{const r=el.getBoundingClientRect();size.current={w:r.width,h:r.height};if(canvas.current){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.current.width=Math.round(r.width*dpr);canvas.current.height=Math.round(r.height*dpr);canvas.current.getContext('2d')?.setTransform(dpr,0,0,dpr,0,0);}};const ro=new ResizeObserver(resize);ro.observe(el);resize();let raf=0,last=0,lastUi=0;
 const frame=(now:number)=>{const s=game.current;if(!s)return;const dt=last?Math.min((now-last)/1000,.04):0;last=now;
 if(!pausedRef.current&&s.status==='playing'&&!s.upgradePending){const i=input.current,k=keys.current;const kx=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0),ky=(k.has('s')||k.has('arrowdown')?1:0)-(k.has('w')||k.has('arrowup')?1:0);let rx=0,ry=0;if(route.current.length&&!kx&&!ky&&joy.current.id===-1){while(route.current.length&&distance(s.p,route.current[0])<8)route.current.shift();if(route.current.length){const pt=route.current[0],dist=distance(s.p,pt);rx=(pt.x-s.p.x)/Math.max(1,dist);ry=(pt.y-s.p.y)/Math.max(1,dist);}}const controls={...i,x:joy.current.id!==-1?i.x:kx||rx,y:joy.current.id!==-1?i.y:ky||ry,interact:i.interact||k.has('e')||interactLatch.current,fire:i.fire||k.has(' '),skill:i.skill};const oldKills=s.kills,oldStep=s.step,oldHits=s.hits;update(s,controls,dt);i.skill=false;if(s.kills>oldKills)beep(650);if(s.step>oldStep){beep(920);interactLatch.current=false;}if(s.nodes[s.step]&&distance(s.p,s.nodes[s.step])>100)interactLatch.current=false;if(s.hits>oldHits)beep(180);
 if(s.upgradePending){input.current=initialInput();keys.current.clear();joy.current.id=-1;setStick({x:0,y:0});}}
 if(canvas.current&&assets.current){const ctx=canvas.current.getContext('2d');if(ctx)render(ctx,s,size.current.w,size.current.h,assets.current);}
 if(now-lastUi>90){lastUi=now;setTick(t=>t+1);}
 raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);
 const kd=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','e','q','escape'].includes(k))e.preventDefault();if(k==='escape'&&!e.repeat){setPaused(p=>!p);return;}if(pausedRef.current)return;route.current=[];interactLatch.current=false;keys.current.add(k);if(k==='q'&&!e.repeat)input.current.skill=true;};const ku=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{interactLatch.current=false;keys.current.clear();input.current=initialInput();joy.current.id=-1;setStick({x:0,y:0});setPaused(true);};const hidden=()=>{if(document.hidden)blur();};window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);return()=>{cancelAnimationFrame(raf);ro.disconnect();window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);};},[playing]);
 const s=game.current;
 useEffect(()=>{if(!s||s.status!=='won'||saved.current)return;saved.current=true;const id=`${s.chapter}-${s.stage}-${s.difficulty}`,entry={score:score(s).total,time:s.time};setRecords(old=>{const prev=old[id],next={...old,[id]:!prev||entry.score>prev.score||entry.score===prev.score&&entry.time<prev.time?entry:prev};try{localStorage.setItem('hse-frontier-records-v1',JSON.stringify(next));}catch{}return next;});},[tick,s]);
 const chosen=HEROES[hero],c=CHAPTERS[chapter];
 function interactDown(e:React.PointerEvent<HTMLButtonElement>){e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pressAt.current=Date.now();interactLatch.current=false;input.current.interact=true;}
 function resetInteract(){input.current.interact=false;}
 function clickInteract(){const g=game.current;if(Date.now()-pressAt.current<300&&g&&g.nodes[g.step]&&distance(g.p,g.nodes[g.step])<100)interactLatch.current=true;}
 function joyMove(e:React.PointerEvent<HTMLDivElement>){if(joy.current.id!==e.pointerId)return;const rect=e.currentTarget.getBoundingClientRect(),dx=e.clientX-(rect.left+rect.width/2),dy=e.clientY-(rect.top+rect.height/2),d=Math.hypot(dx,dy),m=Math.min(1,d/38);input.current.x=d?dx/d*m:0;input.current.y=d?dy/d*m:0;setStick({x:input.current.x*32,y:input.current.y*32});}
 function joyEnd(){joy.current.id=-1;input.current.x=0;input.current.y=0;setStick({x:0,y:0});}
 const modal=playing&&!!s&&(paused||help||s.upgradePending||s.status!=='playing');
 return <main className={playing?'app in-game':'app'} style={{'--hero-color':chosen.color} as CSSProperties}>
 <header className="topbar"><div className="brand"><ShieldCheck size={25}/><strong>安全边界<span>HSE GUARDIANS</span></strong></div><div className="top-actions">{playing&&<span className="mission-tag">{c.name} / {stages[stage]}</span>}<span className="edition">行动版 01</span>{!installed&&<button className="icon-button install-button" aria-label="安装到手机桌面" title="安装到桌面" onClick={requestInstall}><Download size={20}/></button>}<button className="icon-button" aria-label={sound?'关闭音效':'开启音效'} onClick={toggleSound}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button>{playing&&<button className="icon-button" aria-label="暂停游戏" onClick={()=>setPaused(true)}><Pause size={20}/></button>}</div></header>
 {!playing?<div className="lobby"><div className="lobby-intro"><div><div className="eyebrow">选择你的守护者</div><h1>识别危险，<em>安全突围。</em></h1></div><p>四位伙伴，八大现场。<br/>每一次正确行动，都让现场更安全。</p></div>
 <Tabs defaultValue="play" className="lobby-tabs"><TabsList variant="line" className="nav-tabs"><TabsTrigger value="play"><Gamepad2 size={17}/>行动准备</TabsTrigger><TabsTrigger value="atlas"><BookOpen size={17}/>危险图鉴 · 29</TabsTrigger><TabsTrigger value="guide"><ScanLine size={17}/>操作手册</TabsTrigger></TabsList>
 <TabsContent value="play"><section className="hero-grid" aria-label="选择角色">{HEROES.map((h,i)=><button key={h.name} className={'hero-card '+(hero===i?'selected':'')} style={{'--card-color':h.color} as CSSProperties} aria-pressed={hero===i} onClick={()=>setHero(i)}><span className="hero-number">0{i+1} / {h.animal}</span>{hero===i&&<span className="selected-badge"><Check size={13}/>已选择</span>}<Portrait index={i}/><div className="hero-card-bottom"><span className="hero-tag">{h.tag}</span><h2>{h.name}</h2><span className="hero-skill">{h.role}<ArrowRight size={16}/></span></div></button>)}</section>
 <div className="loadout-line"><div className="loadout-title"><Zap size={20}/><b>{chosen.role}</b><span>{chosen.skill}</span></div><p>进场已配基础防护 · 途中拾取工具与增强物资</p></div>
 <section className="mission-select"><div className="section-line"><h2>选择行动现场</h2><span>24个关卡 · 全部可选</span></div><div className="chapter-strip">{CHAPTERS.map((v,i)=>{const done=Object.keys(records).some(k=>k.startsWith(i+'-'));return <button key={v.name} aria-pressed={chapter===i} className={'chapter-card '+(chapter===i?'active':'')} onClick={()=>setChapter(i)}><span>{String(i+1).padStart(2,'0')}{done&&<Check size={14}/>}</span><b>{v.name}</b><small>{v.site}</small></button>})}</div></section>
 <section className="launch-row"><div className="mission-brief"><span className="eyebrow">本次行动</span><h3>{c.sub}</h3><p>{c.knowledge}</p></div><div className="launch-controls"><div className="select-row"><label>关卡<Select value={String(stage)} onValueChange={v=>setStage(Number(v))}><SelectTrigger aria-label="选择关卡"><SelectValue/></SelectTrigger><SelectContent>{stages.map((v,i)=><SelectItem value={String(i)} key={v}>{i+1} · {v}</SelectItem>)}</SelectContent></Select></label><label>难度<Select value={String(difficulty)} onValueChange={v=>setDifficulty(Number(v))}><SelectTrigger aria-label="选择难度"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0">轻松体验</SelectItem><SelectItem value="1">标准行动</SelectItem><SelectItem value="2">进阶挑战</SelectItem></SelectContent></Select></label></div><button className="start-button" onClick={()=>start()} disabled={!assetsReady}>{assetError?'素材加载失败，请刷新':assetsReady?'进入现场':'正在装配行动装备…'}<ArrowRight size={22}/></button></div></section>
 <div className="lobby-foot"><span><Gamepad2 size={16}/>电脑 WASD 移动 / 手机虚拟摇杆 · 默认自动瞄准射击</span><span>预计每关 1—3 分钟</span></div></TabsContent>
 <TabsContent value="atlas"><div className="atlas-intro"><h2>认识危险的不同面孔</h2><p>27类事故主题 + 职业健康、环境污染2类扩展。8组外形家族通过名称、参数与主题区分。<br/>怪物与脉冲是模拟投影；体型、血量不代表真实风险分级。</p><a href="https://www.mem.gov.cn/xw/yjglbgzdt/202601/t20260123_592765.shtml" target="_blank" rel="noreferrer">分类依据：GB 6441—2025 · 应急管理部说明 ↗</a></div><div className="atlas-grid">{HAZARDS.map(h=><article className="atlas-card" key={h.id}><HazardArt sprite={h.sprite}/><span className="eyebrow">{h.extended?'H / E 扩展':`事故主题 ${String(h.id+1).padStart(2,'0')}`}</span><h3>{h.nick}</h3><b>{h.name}</b><p>{h.tip}</p></article>)}</div></TabsContent>
 <TabsContent value="guide"><div className="guide-grid"><article><h2>01 / 怎么操作</h2><p><b>WASD / 方向键</b> 移动<br/><b>E 按住</b> 现场交互<br/><b>Q</b> 专属技能<br/><b>鼠标按住 / 空格</b> 射击<br/><b>Esc</b> 暂停</p><p>手机用左下摇杆移动，右下按钮交互和释放技能。电脑也可双击地面自动绕行；点击左上当前任务可自动寻路。默认自动瞄准并射击；跟随目标箭头前进。</p></article><article><h2>02 / 怎么过关</h2><p>① 检测 → ② 人员撤离 → ③ 源头控制 → ④ 现场保护 → ⑤ 返回报告。</p><p>靠近标号节点，按住交互。源头控制前，首领屏障无法被普通射击击穿。清除残余投影并完成报告即可通关。</p></article><article><h2>03 / 怎么成长</h2><p>接近绿色物资箱即可拾取。每压制3个危险投影获得一次三选一升级。</p><p>必要防护已在进场前配备，拾取物品提供模拟增强。角色、装备均不能让人免疫真实危险。</p></article><article><h2>04 / 怎样评价</h2><p>识别20分、措施35分、撤离25分、现场保护10分、报告10分。</p><p>正确撤离同样能获得满分。生命、速度与技能均为游戏抽象；不替代现场培训、授权、风险评估和操作规程。成绩仅保存在当前浏览器。</p></article></div></TabsContent></Tabs></div>:
 s&&<div className="game-layout"><section className="game-main"><div className="game-hud"><div className="health-block"><span>{chosen.name} <small>模拟生命</small><b>{Math.ceil(s.p.hp)} / 100</b></span><Progress value={s.p.hp} aria-label="模拟生命"/></div><div className="hud-stat"><span>行动时间</span><b>{clock(s.time)}</b></div><div className="hud-stat"><span>成长等级</span><b>Lv.{s.level}</b></div><button className={'auto-button '+(auto?'on':'')} onClick={()=>{setAuto(!auto);s.auto=!auto;}}><Target size={16}/>{auto?'自动射击':'手动射击'}</button></div>
 <div ref={arena} className="arena"><canvas ref={canvas} onDoubleClick={e=>{const r=e.currentTarget.getBoundingClientRect(),cam=camera(s,size.current.w,size.current.h);route.current=findPath(s,{x:(e.clientX-r.left)/cam.scale+cam.x,y:(e.clientY-r.top)/cam.scale+cam.y});}} tabIndex={0} aria-label="HSE动作闯关现场。WASD移动，E交互，Q技能，Esc暂停。" onPointerDown={e=>{if(e.pointerType==='mouse'){e.currentTarget.setPointerCapture(e.pointerId);input.current.fire=true;const r=e.currentTarget.getBoundingClientRect(),cam=camera(s,size.current.w,size.current.h);input.current.aim={x:(e.clientX-r.left)/cam.scale+cam.x,y:(e.clientY-r.top)/cam.scale+cam.y};}}} onPointerMove={e=>{if(e.pointerType==='mouse'){const r=e.currentTarget.getBoundingClientRect(),cam=camera(s,size.current.w,size.current.h);input.current.aim={x:(e.clientX-r.left)/cam.scale+cam.x,y:(e.clientY-r.top)/cam.scale+cam.y};}}} onPointerUp={()=>input.current.fire=false} onPointerCancel={()=>input.current.fire=false}/>
 <button className="arena-mission" aria-label="前往当前任务" onClick={()=>{if(s.nodes[s.step])route.current=findPath(s,s.nodes[s.step]);}}><span>当前任务 {Math.min(s.step+1,5)} / 5</span><b>{s.nodes[s.step]?.label||'行动完成'}</b><small>点击自动寻路</small></button>
 {s.noticeTime>0&&<div className="game-notice" role="status">{s.notice}</div>}
 <div className="touch-controls"><div ref={joyRef} className="joystick" role="group" aria-label="移动摇杆" onPointerDown={e=>{e.preventDefault();if(joy.current.id!==-1)return;route.current=[];joy.current.id=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);joyMove(e);}} onPointerMove={joyMove} onPointerUp={joyEnd} onPointerCancel={joyEnd} onLostPointerCapture={joyEnd}><div className="joystick-cross">＋</div><div className="joystick-knob" style={{transform:`translate(${stick.x}px,${stick.y}px)`}}/></div><div className="action-controls">{!auto&&<button className="fire-button" aria-label="按住射击" onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.current.aim=null;input.current.fire=true;}} onPointerUp={()=>input.current.fire=false} onPointerCancel={()=>input.current.fire=false} onLostPointerCapture={()=>input.current.fire=false}><Target size={22}/><span>射击</span></button>}<button className="skill-button" disabled={s.cd>0} aria-label="释放专属技能" onClick={()=>input.current.skill=true}><Zap size={21}/><span>{s.cd>0?`${Math.ceil(s.cd)}s`:'技能 Q'}</span></button><button className="interact-button" aria-label="现场交互" onClick={clickInteract} onPointerDown={interactDown} onPointerUp={resetInteract} onPointerCancel={resetInteract} onLostPointerCapture={resetInteract}><Hand size={25}/><span>交互 E</span></button></div></div>
 {s.nodes[s.step]&&distance(s.p,s.nodes[s.step])<100&&<div className="near-hint">按住 E 或点击交互按钮</div>}
 </div><div className="game-bottom"><span><ShieldCheck size={15}/>脉冲仅压制危险投影，关键措施决定通关。</span><button onClick={()=>setHelp(true)}>操作说明</button></div></section>
 <aside className="mission-panel"><div className="panel-label">行动档案 <span>0{chapter+1}—0{stage+1}</span></div><h2>{c.name}</h2><p className="panel-sub">{c.site} / {stages[stage]}</p><div className="objective-list">{s.nodes.map((n,i)=><div className={'objective '+(i<s.step?'done':i===s.step?'current':'')} key={i}><span>{i<s.step?<Check size={15}/>:i+1}</span><div><b>{n.label}</b><small>{i<s.step?'已完成':i===s.step?'前往标记点 · 按住交互':'等待前置任务'}</small></div></div>)}</div>
 <div className="boss-status"><div><span>首领危险失控度</span><b>{Math.max(0,Math.ceil((s.enemies.find(e=>e.boss)?.hp||0)/ (s.enemies.find(e=>e.boss)?.max||1)*100))}%</b></div><Progress value={Math.max(0,(s.enemies.find(e=>e.boss)?.hp||0)/(s.enemies.find(e=>e.boss)?.max||1)*100)}/><small>{s.step<3?'源头屏障生效 · 完成第③项解除':'源头屏障已解除 · 可清除残余投影'}</small></div>
 <div className="inventory"><h3>已拾取物资 <span>{s.gear.length}/8</span></h3>{s.gear.length?<div>{s.gear.map((g,i)=><span key={i}>{GEAR[g]}</span>)}</div>:<p>接近绿色物资箱自动拾取</p>}</div><div className="role-note"><Zap size={18}/><div><b>{chosen.role}</b><p>{chosen.skill}</p></div></div><div className="panel-tip">{c.knowledge}</div></aside></div>}
 <Dialog open={installHelp} onOpenChange={setInstallHelp}><DialogContent className="game-dialog install-dialog"><DialogTitle>安装到手机桌面</DialogTitle><DialogDescription>安装后可从桌面启动，并在主要资源已缓存时离线进入游戏。</DialogDescription><div className="install-steps"><p><Share2 size={19}/><span><b>iPhone / iPad</b>使用 Safari 打开，点击“分享”，选择“添加到主屏幕”。</span></p><p><Smartphone size={19}/><span><b>Android</b>使用 Chrome 打开，点击浏览器菜单中的“安装应用”或“添加到主屏幕”。</span></p><small>微信内置浏览器可直接游玩；如需安装，请选择“在浏览器中打开”。</small></div></DialogContent></Dialog>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&s?.status==='playing'&&!s?.upgradePending){setPaused(false);setHelp(false);}}}><DialogContent className="game-dialog" showCloseButton={s?.status==='playing'&&!s?.upgradePending}><DialogTitle>{s?.status==='won'?'行动完成 · 安全归队':s?.status==='lost'?'演练中止 · 重新整备':s?.upgradePending?'现场经验提升':help?'行动操作手册':'行动已暂停'}</DialogTitle><DialogDescription>{s?.status==='won'?'关键措施全部落实，返回集合点完成报告。':s?.status==='lost'?'这次经历会成为下一次正确判断的线索。':s?.upgradePending?'选择一项本局增强。现场时间已暂停。':'准备好后，可以继续当前行动。'}</DialogDescription>
 {s?.upgradePending&&s.status==='playing'?<div className="upgrade-list">{[{icon:Target,title:'精准标记',text:'脉冲效能 +20%'},{icon:Footprints,title:'敏捷行动',text:'移动效率 +8%'},{icon:Hand,title:'工具熟练',text:'交互效率 +25%'}].map((u,i)=><button key={u.title} onClick={()=>{chooseUpgrade(s,i);setTick(t=>t+1);}}><u.icon size={25}/><div><b>{u.title}</b><span>{u.text}</span></div><ArrowRight size={18}/></button>)}</div>:s&&s.status!=='playing'?<><div className="result-score"><ShieldCheck size={34}/><strong>{score(s).total}<small>/ 100</small></strong><span>{s.status==='won'?'现场处置评分':'已完成措施评分'}</span></div><div className="result-stats"><span>行动时间 <b>{clock(s.time)}</b></span><span>投影压制 <b>{s.kills}</b></span><span>受到攻击 <b>{s.hits}</b></span></div><p className="result-tip">{c.knowledge}</p>{s.status==='lost'&&<p>建议：保持移动躲避橙色投射物，优先完成节点任务；首领屏障解除前不必持续攻击。</p>}<div className="dialog-actions"><button className="secondary-button" onClick={home}><Home size={17}/>返回整备</button><button className="primary-button" onClick={()=>s.status==='won'?start(stage<2?chapter:(chapter+1)%8,stage<2?stage+1:0):start()}>{s.status==='won'?'下一关':'重新挑战'}<ArrowRight size={18}/></button></div></>:<><div className="pause-guide"><p><b>移动</b> WASD / 方向键 / 左下摇杆</p><p><b>交互</b> 点击左上任务寻路；靠近后按住 E / 点击右下按钮</p><p><b>技能</b> Q / 闪电按钮</p><p><b>射击</b> 默认自动；手动时按住鼠标 / 空格</p><p>按任务顺序推进，先解除源头屏障，再清除首领的残余投影。</p></div><div className="dialog-actions"><button className="secondary-button" onClick={home}>返回整备</button><button className="primary-button" onClick={()=>{setPaused(false);setHelp(false);}}>继续行动<ArrowRight size={18}/></button></div></>}
 </DialogContent></Dialog>
 </main>;
}
