'use client';
import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,BookOpen,Check,Download,HelpCircle,Lightbulb,Pause,Play,RefreshCw,Shuffle,Smartphone,Volume2,VolumeX,Zap} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {HEROES,SCENES,STAGES,activateHeroSkill,availableMoves,chooseTile,createMatch,resultStars,showHint,shuffleRemaining,tickMatch,type MatchState,type Tile} from '@/lib/game/link-engine';
import {LinkSoundtrack} from '@/lib/game/link-audio';

const basePath=process.env.NEXT_PUBLIC_BASE_PATH??'';
const isNative=Capacitor.isNativePlatform();
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
type Records=Record<string,{score:number;stars:number;time:number}>;
function Portrait({index}:{index:number}){return <span aria-hidden="true" className="portrait" style={{backgroundImage:`url(${basePath}/assets/heroes.webp)`,backgroundPosition:`${index%2*100}% ${Math.floor(index/2)*100}%`}}/>}
function formatTime(value:number){const n=Math.max(0,Math.ceil(value));return `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;}

export default function Page(){
 const [view,setView]=useState<'home'|'atlas'|'play'>('home');
 const [hero,setHero]=useState(0),[scene,setScene]=useState(0),[stage,setStage]=useState(0),[difficulty,setDifficulty]=useState(0);
 const [state,setState]=useState<MatchState|null>(null),[paused,setPaused]=useState(false),[sound,setSound]=useState(true),[help,setHelp]=useState(false),[records,setRecords]=useState<Records>({}),[installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null),[installHelp,setInstallHelp]=useState(false);
 const audio=useRef<LinkSoundtrack|null>(null),lastStatus=useRef(''),saved=useRef(false);
 useEffect(()=>{const load=window.requestAnimationFrame(()=>{try{setRecords(JSON.parse(localStorage.getItem('hse-link-records-v1')||'{}'));}catch{}});if(!isNative&&'serviceWorker'in navigator)void navigator.serviceWorker.register(basePath+'/sw.js',{scope:(basePath||'')+'/'}).catch(()=>{});const before=(e:Event)=>{e.preventDefault();setInstallPrompt(e as InstallPromptEvent)};window.addEventListener('beforeinstallprompt',before);return()=>{window.cancelAnimationFrame(load);window.removeEventListener('beforeinstallprompt',before)}},[]);
 const updateState=useCallback((mutate:(s:MatchState)=>void)=>setState(old=>{if(!old)return old;const next=structuredClone(old);mutate(next);return next}),[]);
 const gameStatus=state?.status;
 useEffect(()=>{if(view!=='play'||paused||help||gameStatus!=='playing')return;const id=window.setInterval(()=>updateState(s=>tickMatch(s,.1)),100);return()=>clearInterval(id)},[view,paused,help,gameStatus,updateState]);
 useEffect(()=>{if(!state)return;audio.current?.update(state,paused||help);if(state.status!==lastStatus.current){if(state.status==='won')audio.current?.cue('win');if(state.status==='lost')audio.current?.cue('lost');lastStatus.current=state.status;}if(state.status==='won'&&!saved.current){saved.current=true;const key=`${state.scene}-${state.stage}-${state.difficulty}`,entry={score:state.score,stars:resultStars(state),time:state.time};setRecords(old=>{const prev=old[key],next={...old,[key]:!prev||entry.stars>prev.stars||entry.stars===prev.stars&&entry.score>prev.score?entry:prev};try{localStorage.setItem('hse-link-records-v1',JSON.stringify(next))}catch{}return next;});}},[state,paused,help]);
 useEffect(()=>{const stop=()=>setPaused(true);const hidden=()=>{if(document.hidden)stop()};window.addEventListener('blur',stop);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',hidden)}},[]);
 function ensureAudio(){try{audio.current??=new LinkSoundtrack();audio.current.setEnabled(sound);return audio.current}catch{return null}}
 function start(nextScene=scene,nextStage=stage){const next=createMatch(nextScene,nextStage,difficulty,hero);setScene(nextScene);setStage(nextStage);setState(next);setPaused(false);setHelp(false);setView('play');saved.current=false;lastStatus.current='playing';ensureAudio()?.start(nextScene);}
 function backHome(){audio.current?.setEnabled(false);setView('home');setState(null);setPaused(false)}
 function tileClick(tile:Tile){updateState(s=>{const result=chooseTile(s,tile.id);if(result==='matched')audio.current?.cue('match');if(result==='wrong')audio.current?.cue('wrong');if(result==='selected')audio.current?.cue('tap')})}
 function skill(){updateState(s=>{if(activateHeroSkill(s))audio.current?.cue('skill')})}
 function hint(){updateState(s=>{if(showHint(s))audio.current?.cue('hint')})}
 function shuffle(){updateState(s=>{if(shuffleRemaining(s,true))audio.current?.cue('shuffle')})}
 function toggleSound(){const next=!sound;setSound(next);ensureAudio()?.setEnabled(next)}
 async function install(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)}else setInstallHelp(true)}
 if(view==='play'&&state)return <GameScreen s={state} paused={paused} help={help} sound={sound} setPaused={setPaused} setHelp={setHelp} onHome={backHome} onSound={toggleSound} onTile={tileClick} onHint={hint} onShuffle={shuffle} onSkill={skill} onRetry={()=>start()} onNext={()=>start((scene+(stage===2?1:0))%SCENES.length,(stage+1)%3)}/>;
 return <main className="shell" style={{'--accent':HEROES[hero].color} as CSSProperties}>
  <header className="topbar"><button className="brand" onClick={()=>setView('home')}><span>安</span><b>安全边界<small>风险连连看</small></b></button><nav><button className={view==='home'?'active':''} onClick={()=>setView('home')}><Play/>开始</button><button className={view==='atlas'?'active':''} onClick={()=>setView('atlas')}><BookOpen/>安全图谱</button></nav><div className="head-actions">{!isNative&&<button aria-label="安装到手机" onClick={install}><Download/></button>}<button aria-label={sound?'关闭声音':'开启声音'} onClick={toggleSound}>{sound?<Volume2/>:<VolumeX/>}</button></div></header>
  {view==='home'?<div className="lobby">
   <section className="intro"><div><span className="kicker">四位守护者 · 十二类现场 · 三十六关</span><h1>连接线索，<em>让风险在现场消失。</em></h1><p>点击两张存在安全关联的牌，用不超过两个转弯的路线完成连接。</p></div><div className="intro-mark"><b>{SCENES.filter(s=>s.category==='工程施工').length}</b><span>类工程施工场景<br/>占首版场景 2/3</span></div></section>
   <section className="panel"><div className="section-title"><div><span>01</span><h2>选择守护者</h2></div><small>每位角色都能独立通关</small></div><div className="hero-grid">{HEROES.map((h,i)=><button key={h.name} className={'hero-card '+(hero===i?'selected':'')} onClick={()=>setHero(i)} style={{'--hero':h.color} as CSSProperties}><Portrait index={i}/><span className="hero-copy"><small>{h.animal} · {h.role}</small><b>{h.name}</b><em>{h.skill}</em><i>{h.desc}</i></span>{hero===i&&<Check className="picked"/>}</button>)}</div></section>
   <section className="panel"><div className="section-title"><div><span>02</span><h2>选择行动现场</h2></div><small>工程项目优先，也保留典型生产场景</small></div><div className="category-line"><b>工程施工 · 8</b><span>动火、高处、吊装、临电、基坑、拆除、管网、检维修</span></div><div className="scene-grid">{SCENES.map((v,i)=>{const stars=Object.entries(records).filter(([k])=>k.startsWith(i+'-')).reduce((n,[,r])=>n+r.stars,0);return <button key={v.name} className={'scene-card '+(scene===i?'selected':'')} onClick={()=>setScene(i)} style={{'--scene':v.color} as CSSProperties}><span className="scene-icon">{v.icon}</span><span><small>{v.category}</small><b>{v.name}</b><i>{v.site}</i></span><em>{stars?`★ ${stars}`:'未行动'}</em></button>})}</div></section>
   <section className="launch panel"><div className="mission"><span className="kicker">当前任务</span><h2>{SCENES[scene].name} · {STAGES[stage].name}</h2><p>{SCENES[scene].mechanic}</p><blockquote>{SCENES[scene].knowledge}</blockquote></div><div className="settings"><label>关卡<select value={stage} onChange={e=>setStage(Number(e.target.value))}>{STAGES.map((v,i)=><option value={i} key={v.name}>{i+1} · {v.name}</option>)}</select></label><label>节奏<select value={difficulty} onChange={e=>setDifficulty(Number(e.target.value))}><option value={0}>轻松体验</option><option value={1}>标准行动</option><option value={2}>进阶挑战</option></select></label><button className="primary" onClick={()=>start()}>进入现场 <Play/></button><small>单局约2—4分钟 · 支持触屏 · 可离线游玩</small></div></section>
  </div>:<Atlas/>}
  {installHelp&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setInstallHelp(false)}>×</button><Smartphone className="modal-icon"/><h2>安装到手机</h2><p>Android请使用浏览器菜单中的“安装应用”或“添加到主屏幕”；iPhone请使用Safari的“分享—添加到主屏幕”。APK版本可从仓库工作流产物下载。</p><button className="primary" onClick={()=>setInstallHelp(false)}>知道了</button></div></div>}
 </main>
}

function Atlas(){return <div className="atlas"><section className="intro compact"><div><span className="kicker">安全图谱</span><h1>不是背答案，<em>是理解关联。</em></h1><p>牌面将事故线索、危险状态、控制措施与复核要求组成可迁移的安全链。</p></div></section><div className="atlas-groups">{SCENES.map((scene,i)=><article key={scene.name} style={{'--scene':scene.color} as CSSProperties}><header><span>{scene.icon}</span><div><small>{scene.category} · {String(i+1).padStart(2,'0')}</small><h2>{scene.name}</h2></div></header><p>{scene.knowledge}</p><div>{scene.pairs.slice(0,4).map((pair,j)=><span className="pair-chip" key={j}>{pair.a.icon} {pair.a.label}<b>↔</b>{pair.b.icon} {pair.b.label}</span>)}</div></article>)}</div><p className="boundary">游戏内容为教学抽象，不替代现场风险评估、专项方案、作业许可、操作规程、专业授权或岗位培训。</p></div>}

function GameScreen({s,paused,help,sound,setPaused,setHelp,onHome,onSound,onTile,onHint,onShuffle,onSkill,onRetry,onNext}:{s:MatchState;paused:boolean;help:boolean;sound:boolean;setPaused:(v:boolean)=>void;setHelp:(v:boolean)=>void;onHome:()=>void;onSound:()=>void;onTile:(t:Tile)=>void;onHint:()=>void;onShuffle:()=>void;onSkill:()=>void;onRetry:()=>void;onNext:()=>void}){
 const scene=SCENES[s.scene],hero=HEROES[s.hero],remain=s.timeLimit-s.time,progress=s.matches/s.totalPairs*100;
 const path=s.lastPathUntil>s.time?s.lastPath.map(p=>`${p.col+.5},${p.row+.5}`).join(' '):'';
 return <main className="game" style={{'--scene':scene.color,'--hero':hero.color} as CSSProperties}>
  <header className="game-head"><button onClick={onHome} aria-label="返回大厅"><ArrowLeft/></button><div><small>{scene.category} · {STAGES[s.stage].name}</small><b>{scene.icon} {scene.name}</b></div><div><button onClick={onSound}>{sound?<Volume2/>:<VolumeX/>}</button><button onClick={()=>setHelp(true)}><HelpCircle/></button><button onClick={()=>setPaused(true)}><Pause/></button></div></header>
  <section className="game-body"><aside className="status-panel"><div className="operative"><Portrait index={s.hero}/><span><small>{hero.role}</small><b>{hero.name}</b><i>{hero.skill}</i></span></div><div className="objective"><small>现场任务</small><b>{STAGES[s.stage].brief}</b><p>{scene.mechanic}</p></div><div className="desktop-tools"><button onClick={onHint}><Lightbulb/>提示</button><button onClick={onShuffle} disabled={!s.shuffleCharges}><Shuffle/>重排 ×{s.shuffleCharges}</button><button className="skill" onClick={onSkill} disabled={!s.skillCharges}><Zap/>{hero.skill} ×{s.skillCharges}</button></div><p className="knowledge">{scene.knowledge}</p></aside>
   <div className="play-column"><div className="hud"><div><small>剩余时间</small><b className={remain<20?'danger':''}>{formatTime(remain)}</b></div><div><small>安全连击</small><b>× {s.combo}</b></div><div><small>行动得分</small><b>{s.score}</b></div></div><div className="progress"><i style={{width:`${progress}%`}}/><span>{s.matches} / {s.totalPairs}</span></div>
    <div className={'board-wrap '+(s.fogUntil>s.time?'fogged':'')}><div className="site-backdrop"><span>{scene.icon}</span><b>{scene.eventName}</b></div><div className="board" role="grid" aria-label={`${scene.name}连连看棋盘`}>{Array.from({length:s.rows*s.cols},(_,i)=>{const row=Math.floor(i/s.cols),col=i%s.cols,t=s.tiles.find(x=>!x.removed&&x.row===row&&x.col===col);if(!t)return <span className="cell empty" key={i}/>;const pair=scene.pairs[t.pairIndex],face=pair[t.face],selected=s.selected===t.id,hinted=s.hint.includes(t.id),locked=t.lockedUntil>s.time;return <button role="gridcell" key={t.id} className={`tile ${selected?'selected':''} ${hinted?'hinted':''} ${locked?'locked':''}`} onClick={()=>onTile(t)} disabled={locked} aria-label={`${face.label}，${pair.kind}类牌`}><span>{face.icon}</span><b>{face.label}</b><small>{pair.kind}</small>{locked&&<i>受阻</i>}</button>})}<svg className="link-line" viewBox="-.7 -.7 7.4 7.4" preserveAspectRatio="none" aria-hidden="true">{path&&<polyline points={path} vectorEffect="non-scaling-stroke"/>}</svg></div></div>
    <div className="notice" aria-live="polite"><b>{s.noticeUntil>s.time?s.notice:'寻找下一组安全关联'}</b><span>{availableMoves(s).length} 组当前可连接</span></div>
    <div className="mobile-tools"><button onClick={onHint}><Lightbulb/><span>提示</span></button><button onClick={onShuffle} disabled={!s.shuffleCharges}><Shuffle/><span>重排 {s.shuffleCharges}</span></button><button className="skill" onClick={onSkill} disabled={!s.skillCharges}><Zap/><span>{hero.skill} {s.skillCharges}</span></button></div>
   </div>
  </section>
  {(paused||help||s.status!=='playing')&&<div className="overlay"><div className="modal result">{s.status==='won'?<><span className="result-icon">{scene.icon}</span><small>现场已受控</small><h2>{'★'.repeat(resultStars(s))}{'☆'.repeat(3-resultStars(s))}</h2><p>得分 {s.score} · 最佳连击 {s.bestCombo} · 错配 {s.mistakes}</p><blockquote>{scene.knowledge}</blockquote><div><button onClick={onHome}>返回大厅</button><button className="primary" onClick={onNext}>下一关 <Play/></button></div></>:s.status==='lost'?<><span className="result-icon">⏱️</span><small>处置窗口结束</small><h2>现场风险仍未受控</h2><p>已完成 {s.matches}/{s.totalPairs} 组连接。可以降低节奏或使用角色技能重新挑战。</p><div><button onClick={onHome}>返回大厅</button><button className="primary" onClick={onRetry}>重新行动 <RefreshCw/></button></div></>:help?<><HelpCircle className="modal-icon"/><h2>如何连接</h2><p>依次点击两张存在正确安全关联的牌。如果它们能通过不超过两个转弯的空白路线连接，即可消除。</p><ul><li>同类事故表现不一定能互相消除，重点看线索与措施之间的关系。</li><li>现场事件每完成4组触发一次。</li><li>角色技能不会改变专业规则，只提供信息或排列优势。</li></ul><button className="primary" onClick={()=>setHelp(false)}>继续行动</button></>:<><Pause className="modal-icon"/><h2>行动已暂停</h2><p>倒计时和现场事件均已停止。</p><div><button onClick={onHome}>返回大厅</button><button className="primary" onClick={()=>setPaused(false)}>继续行动 <Play/></button></div></>}</div></div>}
 </main>
}
