import {WORLD,HEROES,HAZARDS,CHAPTERS,GEAR,clamp,distance,type State} from './engine';
export type Assets={heroes:HTMLImageElement,hazards:HTMLImageElement,floor:HTMLImageElement};
export type Camera={x:number,y:number,scale:number,w:number,h:number};
export function camera(s:State,w:number,h:number):Camera{const scale=w<650?.83:Math.min(1.08,w/1020);const vw=w/scale,vh=h/scale;return {x:clamp(s.p.x-vw/2,0,Math.max(0,WORLD.w-vw)),y:clamp(s.p.y-vh/2,0,Math.max(0,WORLD.h-vh)),scale,w:vw,h:vh};}
function box(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,fill:string,stroke?:string,r=8){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function label(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,color='#deedf0',size=14){ctx.fillStyle=color;ctx.font=`600 ${size}px system-ui, sans-serif`;ctx.textAlign='center';ctx.fillText(text,x,y);}
function sprite(ctx:CanvasRenderingContext2D,img:HTMLImageElement,index:number,cols:number,rows:number,x:number,y:number,size:number){if(!img.complete||!img.naturalWidth)return;const sw=img.naturalWidth/cols,sh=img.naturalHeight/rows;ctx.drawImage(img,(index%cols)*sw,Math.floor(index/cols)*sh,sw,sh,x-size/2,y-size*.72,size,size);}
export function render(ctx:CanvasRenderingContext2D,s:State,w:number,h:number,assets:Assets){
 const c=camera(s,w,h),theme=CHAPTERS[s.chapter].color;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0e202a';ctx.fillRect(0,0,w,h);ctx.save();ctx.scale(c.scale,c.scale);ctx.translate(-c.x,-c.y);
 if(assets.floor.complete&&assets.floor.naturalWidth){ctx.globalAlpha=.7;ctx.drawImage(assets.floor,0,0,WORLD.w,WORLD.h);ctx.globalAlpha=1;}ctx.fillStyle='#07192266';ctx.fillRect(0,0,WORLD.w,WORLD.h);
 ctx.strokeStyle='#5f969414';ctx.lineWidth=1;for(let x=0;x<WORLD.w;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.h);ctx.stroke();}for(let y=0;y<WORLD.h;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.w,y);ctx.stroke();}
 ctx.strokeStyle=theme+'55';ctx.lineWidth=3;ctx.strokeRect(25,25,WORLD.w-50,WORLD.h-50);
 label(ctx,CHAPTERS[s.chapter].site,710,80,'#8ea7b777',27);
 // Blueprint blocks represent impassable equipment zones, with collision boundaries matching the geometry.
 for(const b of s.blocks){box(ctx,b.x+6,b.y+8,b.w,b.h,'#00000044');box(ctx,b.x,b.y,b.w,b.h,'#142d37','#527581',10);box(ctx,b.x+12,b.y+12,b.w-24,b.h-24,'#0b202b','#34505b',5);ctx.save();ctx.beginPath();ctx.rect(b.x+15,b.y+15,b.w-30,b.h-30);ctx.clip();ctx.strokeStyle='#294751';for(let k=-b.h;k<b.w;k+=22){ctx.beginPath();ctx.moveTo(b.x+k,b.y);ctx.lineTo(b.x+k+b.h,b.y+b.h);ctx.stroke();}ctx.restore();label(ctx,b.label,b.x+b.w/2,b.y+b.h/2,'#aac5ce',16);label(ctx,'隔离区域 · 不可穿越',b.x+b.w/2,b.y+b.h/2+26,'#76919d',12);}
 for(let i=0;i<s.nodes.length;i++){const n=s.nodes[i],done=i<s.step,active=i===s.step,col=done?'#72e8b4':active?theme:'#506b79';ctx.setLineDash(active?[8,6]:[]);ctx.strokeStyle=col;ctx.lineWidth=active?2:1;ctx.beginPath();ctx.arc(n.x,n.y,active?50+Math.sin(s.time*3)*3:35,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);box(ctx,n.x-23,n.y-23,46,46,done?'#174835':'#152f39',col,12);label(ctx,done?'✓':String(i+1),n.x,n.y+7,col,22);label(ctx,n.label,n.x,n.y+71,col,15);if(active&&s.progress){ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(n.x,n.y,57,-Math.PI/2,-Math.PI/2+Math.PI*2*s.progress/1.65);ctx.stroke();}}
 for(const p of s.pickups){if(p.taken)continue;const bounce=Math.sin(s.time*3+p.kind)*3;ctx.shadowColor='#b9e479';ctx.shadowBlur=10;box(ctx,p.x-16,p.y-16+bounce,32,32,'#2a4836','#b9e479',8);ctx.shadowBlur=0;label(ctx,['帽','镜','具','检','电','＋','鞋','讯'][p.kind],p.x,p.y+6+bounce,'#d8fdb2',17);if(distance(s.p,p)<150||s.buff>0&&s.hero===3)label(ctx,GEAR[p.kind],p.x,p.y+38,'#c2d2bd',13);}
 for(const e of [...s.enemies].sort((a,b)=>a.y-b.y)){if(e.dead)continue;const hz=HAZARDS[e.type];ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(e.x,e.y+14,e.r*.85,e.r*.38,0,0,Math.PI*2);ctx.fill();sprite(ctx,assets.hazards,hz.sprite,4,2,e.x,e.y+(Math.sin(s.time*3+e.id)*2),e.r*2.75);if(e.flash>0){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,e.r+5,0,Math.PI*2);ctx.stroke();}
 if(e.boss&&s.step<3){ctx.strokeStyle='#ffd36ab0';ctx.setLineDash([9,7]);ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,e.r+15,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
 const bar=e.boss?110:55;box(ctx,e.x-bar/2,e.y-e.r-35,bar,5,'#091b24');box(ctx,e.x-bar/2,e.y-e.r-35,bar*Math.max(0,e.hp/e.max),5,hz.color);if(e.boss||distance(s.p,e)<270||s.buff>0&&s.hero===1)label(ctx,(e.boss?'首领 · ':'')+hz.nick,e.x,e.y-e.r-43,hz.color,e.boss?15:12);
 }
 for(const b of s.shotsList){ctx.fillStyle=b.enemy?'#ff986f':'#b8ffee';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=b.enemy?5:10;ctx.beginPath();ctx.arc(b.x,b.y,b.enemy?6:3.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}
 ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(s.p.x,s.p.y+23,25,9,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=HEROES[s.hero].color;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(s.p.x,s.p.y+23,28,11,0,0,Math.PI*2);ctx.stroke();if(s.p.inv>0&&Math.floor(s.time*14)%2===0)ctx.globalAlpha=.55;sprite(ctx,assets.heroes,s.hero,2,2,s.p.x,s.p.y+7,95);ctx.globalAlpha=1;label(ctx,HEROES[s.hero].name,s.p.x,s.p.y-72,HEROES[s.hero].color,14);
 for(const r of s.rings){ctx.globalAlpha=Math.max(0,r.ttl/r.max);ctx.strokeStyle=r.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke();if(r.label)label(ctx,r.label,r.x,r.y-r.r,r.color,17);ctx.globalAlpha=1;}
 ctx.restore();
 const goal=s.nodes[s.step];if(goal){const gx=(goal.x-c.x)*c.scale,gy=(goal.y-c.y)*c.scale;if(gx<60||gx>w-60||gy<60||gy>h-60){const a=Math.atan2(gy-h/2,gx-w/2),ex=clamp(gx,40,w-40),ey=clamp(gy,55,h-60);ctx.save();ctx.translate(ex,ey);ctx.rotate(a);ctx.fillStyle=theme;ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-8,-9);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.restore();label(ctx,String(s.step+1),ex,ey-20,theme,18);}}
 // Compact whole-map locator.
 const mw=w<500?96:130,mh=mw*2/3,mx=w-mw-14,my=14;box(ctx,mx-5,my-5,mw+10,mh+10,'#071620da','#4b6b7766');ctx.save();ctx.translate(mx,my);ctx.scale(mw/WORLD.w,mh/WORLD.h);for(const b of s.blocks){ctx.fillStyle='#43606b';ctx.fillRect(b.x,b.y,b.w,b.h);}s.nodes.forEach((n,i)=>{ctx.fillStyle=i<s.step?'#74e5b3':i===s.step?theme:'#536b76';ctx.beginPath();ctx.arc(n.x,n.y,30,0,Math.PI*2);ctx.fill();});ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.p.x,s.p.y,28,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffffff77';ctx.lineWidth=9;ctx.strokeRect(c.x,c.y,Math.min(c.w,WORLD.w),Math.min(c.h,WORLD.h));ctx.restore();
 if(s.p.hp<30){ctx.strokeStyle='#ff7b6977';ctx.lineWidth=8+Math.sin(s.time*4)*3;ctx.strokeRect(0,0,w,h);}
}
